/**
 * Shared message types for WebSocket communication
 */
export const MSG_TYPES = {
  // Client registration
  REGISTER_GAME: 'REGISTER_GAME',
  REGISTER_CONTROLLER: 'REGISTER_CONTROLLER',

  // Connection status broadcast
  STATUS_UPDATE: 'STATUS_UPDATE',

  // Gameplay actions
  ORIENTATION: 'ORIENTATION',
  SHOOT: 'SHOOT',
  RECENTER: 'RECENTER',

  // Settings and multiplayer events
  SETTINGS_UPDATE: 'SETTINGS_UPDATE',
  PLAYER_CONNECTED: 'PLAYER_CONNECTED',
  PLAYER_DISCONNECTED: 'PLAYER_DISCONNECTED',
  START_GAME: 'START_GAME',
  PLAYER_HIT: 'PLAYER_HIT',
  PLAYER_STATS: 'PLAYER_STATS',
  RESET_STATS: 'RESET_STATS',
  RETURN_TO_LOBBY: 'RETURN_TO_LOBBY'
};

/**
 * Connection states for clients
 */
export const CONNECTION_STATES = {
  WAITING: 'WAITING',
  CONNECTED: 'CONNECTED',
  DISCONNECTED: 'DISCONNECTED'
};
